apiVersion: v1
kind: ServiceAccount
metadata:
  name: elb-inject
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: elb-inject
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: elb-inject-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elb-inject
subjects:
- kind: ServiceAccount
  name: elb-inject
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elb-inject
spec:
  selector:
    matchLabels:
      app: elb-inject
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elb-inject
    spec:
      serviceAccountName: elb-inject
      containers:
      - name: elb-inject
        image: duym/elb-inject:latest
        imagePullPolicy: Always
